// Standard source catalog (data-first).
// Add new sources here instead of hardcoding arrays in modal.js.
window.SOURCE_CATALOG = [
	{
		id: "asura",
		name: "Asura Scans",
		icon: "⚔️",
		type: "fantl",
		mode: "templated",
		priority: 1,
		slugger: "basic",
		series_template: "https://asurascans.com/comics/{slug}-75e30c62",
		chapter_template: "https://asurascans.com/comics/{slug}-75e30c62/chapter/{chapter}",
	},
	{
		id: "demonic",
		name: "Demonic Scans",
		icon: "😈",
		type: "fantl",
		mode: "demonic",
		priority: 2,
	},
	{
		id: "adk",
		name: "ADK Scans",
		icon: "☄️",
		type: "fantl",
		mode: "templated",
		priority: 3,
		slugger: "basic",
		series_template: "https://www.silentquill.net/{slug}/",
		chapter_template: "https://www.silentquill.net/{slug}-chapter-{chapter}/",
	},
	{
		id: "reaper",
		name: "Reaper Scans",
		icon: "🗡️",
		type: "fantl",
		mode: "search_only",
		priority: 10,
		search_template: "https://reaperscans.com/?s={query}",
	},
	{
		id: "flame",
		name: "Flame Comics",
		icon: "🔥",
		type: "fantl",
		mode: "search_only",
		priority: 11,
		search_template: "https://flamecomics.com/?s={query}",
	},
	{
		id: "realm",
		name: "Realm Scans",
		icon: "🛡️",
		type: "fantl",
		mode: "search_only",
		priority: 12,
		search_template: "https://realmscans.com/?s={query}",
	},
];
